name: Corellium

on: [push]

jobs:
  corellium:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Corellium CLI
        run: npm install -g @corellium/corellium-cli
      
      - name: Login to Corellium
        run: corellium login --apitoken ${{ secrets.CORELLIUM_API_TOKEN }} --endpoint ${{ secrets.CORELLIUM_SERVER }}
      
      - name: Create device
        # The `true` argument will wait for the device to be ready before continuing, which is useful for CI.
        # We'll store the device ID in an environment variable so we can use it later.
        run: |
          id=$(corellium instance create imx93 2.1.0 ${{ secrets.CORELLIUM_PROJECT }} Github-imx93)
          echo "instanceId=$id" >> $GITHUB_ENV
